import { jsPDF } from 'jspdf';

// ── HELPER GRAPHICS & COMPONENTS ──

function drawWatermark(doc: jsPDF, text: string) {
  doc.setTextColor(245, 247, 250);
  doc.setFontSize(70);
  doc.setFont('helvetica', 'bold');
  const w = doc.internal.pageSize.width;
  const h = doc.internal.pageSize.height;
  // @ts-ignore
  doc.text(text, w / 2, h / 2 + 20, { angle: 45, align: 'center' });
}

function drawHeader(doc: jsPDF, title: string, id: string) {
  const w = doc.internal.pageSize.width;
  
  // Top brand bar
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, w, 6, 'F');
  
  // Header background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 6, w, 34, 'F');
  
  // Logo
  doc.setTextColor(37, 99, 235); // blue-600
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('LoanIQ', 15, 25);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text('INTELLIGENT LENDING SYSTEMS', 16, 32);

  // Title
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title.toUpperCase(), w - 15, 22, { align: 'right' });
  
  // Mock Barcode for Application ID
  doc.setFillColor(0, 0, 0);
  let barX = w - 65;
  const safeId = id || 'UNKNOWN';
  for (let i = 0; i < 20; i++) {
    const barW = (safeId.charCodeAt(i % safeId.length) % 3) + 0.5;
    doc.rect(barX, 26, barW, 8, 'F');
    barX += barW + 1;
  }
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(`REF: ${safeId}`, w - 15, 37, { align: 'right' });

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(1);
  doc.line(15, 42, w - 15, 42);
}

function drawFooter(doc: jsPDF) {
  const h = doc.internal.pageSize.height;
  const w = doc.internal.pageSize.width;
  
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(15, h - 15, w - 15, h - 15);
  
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by LoanIQ Secure Engine • ${new Date().toLocaleString()}`, 15, h - 10);
  doc.text('CONFIDENTIAL & PROPRIETARY', w - 15, h - 10, { align: 'right' });
}

function drawBox(doc: jsPDF, x: number, y: number, w: number, h: number, title: string) {
  // Shadow mock
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(x + 1, y + 1, w, h, 2, 2, 'F');
  
  // Box
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, 'FD');
  
  // Title ribbon
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(x, y, w, 8, 2, 2, 'F');
  // straight line to cover bottom rounded corners of ribbon
  doc.rect(x, y + 6, w, 2, 'F');
  doc.line(x, y + 8, x + w, y + 8);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text(title.toUpperCase(), x + 4, y + 5.5);
}

function drawDataRow(doc: jsPDF, startX: number, startY: number, items: {l: string, v: string, c?: [number,number,number]}[], colW: number) {
  items.forEach((item, i) => {
    const x = startX + (i * colW);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text(item.l.toUpperCase(), x, startY);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    if (item.c) {
      doc.setTextColor(item.c[0], item.c[1], item.c[2]);
    } else {
      doc.setTextColor(15, 23, 42);
    }
    doc.text(String(item.v || 'N/A'), x, startY + 4);
  });
}

function drawGauge(doc: jsPDF, x: number, y: number, w: number, score: number) {
  const h = 4;
  const min = 300, max = 900;
  const val = Math.max(min, Math.min(max, score || 0));
  const p = (val - min) / (max - min);
  
  // Background tracks
  doc.setFillColor(239, 68, 68); // Red
  doc.rect(x, y, w * 0.35, h, 'F');
  doc.setFillColor(245, 158, 11); // Yellow
  doc.rect(x + w * 0.35, y, w * 0.35, h, 'F');
  doc.setFillColor(34, 197, 94); // Green
  doc.rect(x + w * 0.70, y, w * 0.30, h, 'F');
  
  // Marker
  const mx = x + (w * p);
  doc.setFillColor(15, 23, 42);
  doc.triangle(mx, y - 1, mx - 2, y - 4, mx + 2, y - 4, 'F');
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(0.5);
  doc.line(mx, y, mx, y + h);
  
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'normal');
  doc.text('300', x, y + h + 4);
  doc.text('900', x + w, y + h + 4, { align: 'right' });
  
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text(val.toString(), mx, y - 5, { align: 'center' });
}

// ── GENERATORS ──

export function generateApplicationReviewPDF(app: any) {
  const doc = new jsPDF();
  drawWatermark(doc, 'INTERNAL REVIEW');
  drawHeader(doc, 'Credit Application Review', app.id);
  
  const w = doc.internal.pageSize.width;
  let y = 50;
  
  // Status Ribbon
  doc.setFillColor(app.decision === 'APPROVED' ? 34 : (app.decision === 'REJECTED' ? 239 : 245), 
                   app.decision === 'APPROVED' ? 197 : (app.decision === 'REJECTED' ? 68 : 158), 
                   app.decision === 'APPROVED' ? 94 : (app.decision === 'REJECTED' ? 68 : 11));
  doc.rect(15, y, w - 30, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`CURRENT STATUS: ${app.decision || 'PENDING'}`, w / 2, y + 5.5, { align: 'center' });
  y += 15;
  
  // Applicant Box
  drawBox(doc, 15, y, w - 30, 25, '1. Applicant Profile');
  drawDataRow(doc, 20, y + 14, [
    { l: 'Full Legal Name', v: app.customerDetails?.name },
    { l: 'PAN ID', v: app.customerDetails?.panNumber },
    { l: 'Application Date', v: app.createdAt ? new Date(app.createdAt).toLocaleDateString() : 'N/A' }
  ], (w - 40) / 3);
  y += 30;
  
  // Financial Box
  drawBox(doc, 15, y, w - 30, 35, '2. Financial Snapshot');
  drawDataRow(doc, 20, y + 14, [
    { l: 'Requested Amount', v: `INR ${(app.financialDetails?.requestedAmount || 0).toLocaleString()}` },
    { l: 'Reported Income', v: `INR ${(app.financialDetails?.income || 0).toLocaleString()}` },
    { l: 'Employment Status', v: app.financialDetails?.jobType }
  ], (w - 40) / 3);
  drawDataRow(doc, 20, y + 26, [
    { l: 'Loan Purpose', v: app.financialDetails?.loanPurpose },
    { l: 'Calculated Risk Tier', v: app.riskLevel, c: app.riskLevel === 'LOW' ? [34,197,94] : [239,68,68] }
  ], (w - 40) / 3);
  y += 40;
  
  // Credit Gauge & AI Box
  drawBox(doc, 15, y, w - 30, 50, '3. AI Underwriting & Credit Risk');
  
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'normal');
  doc.text('CREDIT SCORE METER', 20, y + 15);
  drawGauge(doc, 20, y + 25, 80, app.creditScore || 0);
  
  doc.setDrawColor(226, 232, 240);
  doc.line(110, y + 12, 110, y + 45); // vertical divider
  
  doc.text('AI UNDERWRITING SUMMARY', 115, y + 15);
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  if (app.explanation) {
    const splitText = doc.splitTextToSize(app.explanation, w - 135);
    doc.text(splitText, 115, y + 21);
  } else {
    doc.text('No AI explanation provided.', 115, y + 21);
  }

  drawFooter(doc);
  doc.save(`LoanIQ_Credit_Review_${app.id?.substring(0, 8).toUpperCase() || 'Report'}.pdf`);
}

export function generateKYCVerificationPDF(app: any) {
  const doc = new jsPDF();
  drawWatermark(doc, 'KYC AUDIT');
  drawHeader(doc, 'KYC Compliance Report', app.id);
  
  const w = doc.internal.pageSize.width;
  let y = 50;
  
  // Subject Box
  drawBox(doc, 15, y, w - 30, 25, 'Subject Identity Information');
  drawDataRow(doc, 20, y + 14, [
    { l: 'Subject Name', v: app.customerDetails?.name },
    { l: 'Tax ID (PAN)', v: app.customerDetails?.panNumber },
    { l: 'Audit Date', v: new Date().toLocaleDateString() }
  ], (w - 40) / 3);
  y += 30;
  
  // Checks Box
  drawBox(doc, 15, y, w - 30, 45, 'Automated Verification Matrix');
  
  const isLivenessPass = !!app.verification?.liveness;
  const isPanVerified = !!app.verification?.panVerified;
  
  drawDataRow(doc, 20, y + 14, [
    { l: 'Liveness Confidence Check', v: isLivenessPass ? 'VERIFIED' : 'FAILED', c: isLivenessPass ? [34,197,94] : [239,68,68] },
    { l: 'PAN Authority Match', v: isPanVerified ? 'VERIFIED' : 'FAILED', c: isPanVerified ? [34,197,94] : [239,68,68] }
  ], (w - 40) / 2);
  
  // Bar visualization for Face Match
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'normal');
  doc.text('BIOMETRIC FACE MATCH CONFIDENCE', 20, y + 28);
  
  const matchScore = app.verification?.faceMatchScore || 0;
  doc.setFillColor(241, 245, 249);
  doc.rect(20, y + 32, (w - 40), 6, 'F');
  
  doc.setFillColor(matchScore >= 80 ? 34 : (matchScore >= 50 ? 245 : 239), 
                   matchScore >= 80 ? 197 : (matchScore >= 50 ? 158 : 68), 
                   matchScore >= 80 ? 94 : (matchScore >= 50 ? 11 : 68));
  doc.rect(20, y + 32, ((w - 40) * (matchScore / 100)), 6, 'F');
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  if (matchScore > 10) {
    doc.text(`${matchScore}% MATCH`, 22, y + 36.5);
  }
  
  y += 50;
  
  // Conclusion Box
  const isFullyVerified = isLivenessPass && isPanVerified;
  doc.setFillColor(isFullyVerified ? 240 : 254, isFullyVerified ? 253 : 242, isFullyVerified ? 244 : 242);
  doc.setDrawColor(isFullyVerified ? 187 : 252, isFullyVerified ? 247 : 165, isFullyVerified ? 208 : 165);
  doc.setLineWidth(0.5);
  doc.roundedRect(15, y, w - 30, 20, 2, 2, 'FD');
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(isFullyVerified ? 21 : 153, isFullyVerified ? 128 : 27, isFullyVerified ? 61 : 27);
  doc.text(isFullyVerified ? 'COMPLIANCE AUDIT PASSED' : 'COMPLIANCE AUDIT FAILED', w / 2, y + 8, { align: 'center' });
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(isFullyVerified 
    ? 'All automated regulatory and identity checks have cleared successfully.' 
    : 'Identity checks failed. Manual intervention and physical verification required.', 
    w / 2, y + 14, { align: 'center' });

  drawFooter(doc);
  doc.save(`LoanIQ_KYC_Audit_${app.id?.substring(0, 8).toUpperCase() || 'Report'}.pdf`);
}

export function generateSanctionLetter(app: any) {
  // Existing function left intact, using the old helper logic specifically for it if necessary.
  // We'll reimplement it minimally so the file compiles properly.
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // Header Background
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('LoanIQ', 20, 25);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('LOAN SANCTION LETTER', pageWidth - 20, 25, { align: 'right' });
  
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(12);
  
  const today = new Date().toLocaleDateString();
  doc.text(`Date: ${today}`, 20, 60);
  doc.text(`To,`, 20, 75);
  doc.text(`${app.customerDetails?.name || 'Applicant'}`, 20, 83);
  
  doc.setFont('helvetica', 'bold');
  doc.text(`Subject: Sanction of Personal Loan Application (ID: ${app.id})`, 20, 100);
  
  doc.setFont('helvetica', 'normal');
  const amount = app.offer?.offeredAmount || app.financialDetails?.requestedAmount || 0;
  
  const body = `Dear ${app.customerDetails?.name || 'Applicant'},\n\nWe are pleased to inform you that your loan application has been conditionally approved. Please find the details of the sanctioned loan below:\n\n1. Sanctioned Amount: INR ${amount.toLocaleString()}\n2. Interest Rate: ${app.offer?.interestRate || 'Standard'}% p.a.\n3. Tenure: ${app.offer?.tenure || 12} Months\n\nThis sanction is subject to the final verification of submitted documents and acceptance of the terms and conditions. Our disbursement team will contact you shortly.\n\nThank you for choosing LoanIQ.\n\nSincerely,\nLoanIQ Administration Team`;
  
  const splitText = doc.splitTextToSize(body, 170);
  doc.text(splitText, 20, 115);
  
  doc.setDrawColor(200, 200, 200);
  doc.line(20, doc.internal.pageSize.height - 20, pageWidth - 20, doc.internal.pageSize.height - 20);
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated on ${new Date().toLocaleString()}`, 20, doc.internal.pageSize.height - 12);
  doc.text('LoanIQ Secure Document System', pageWidth - 20, doc.internal.pageSize.height - 12, { align: 'right' });
  
  doc.save(`LoanIQ_Sanction_Letter_${app.id?.substring(0, 8).toUpperCase() || 'Letter'}.pdf`);
}
